//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace XmlNotepad {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class SR {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal SR() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("XmlNotepad.SR", typeof(SR).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   使用此强类型资源类，为所有资源查找
        ///   重写当前线程的 CurrentUICulture 属性。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 Add 的本地化字符串。
        /// </summary>
        internal static string AddSchemaCommand {
            get {
                return ResourceManager.GetString("AddSchemaCommand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 A simple XML editor with XSD intellisense and XSLTpreview 的本地化字符串。
        /// </summary>
        internal static string AppDescription {
            get {
                return ResourceManager.GetString("AppDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 XmlNotepad 的本地化字符串。
        /// </summary>
        internal static string AppProgId {
            get {
                return ResourceManager.GetString("AppProgId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Assembly Load Error 的本地化字符串。
        /// </summary>
        internal static string AssemblyLoadCaption {
            get {
                return ResourceManager.GetString("AssemblyLoadCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Could not load assembly &apos;{0}&apos;
        ///Reason:
        ///{1} 的本地化字符串。
        /// </summary>
        internal static string AssemblyLoadError {
            get {
                return ResourceManager.GetString("AssemblyLoadError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Attribute 的本地化字符串。
        /// </summary>
        internal static string AttributeColor {
            get {
                return ResourceManager.GetString("AttributeColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Text color for attributes 的本地化字符串。
        /// </summary>
        internal static string AttributeColorDescription {
            get {
                return ResourceManager.GetString("AttributeColorDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Autoformat long lines instead of prompting 的本地化字符串。
        /// </summary>
        internal static string AutoFormatLongLinesDescriptions {
            get {
                return ResourceManager.GetString("AutoFormatLongLinesDescriptions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Autoformat Long Lines 的本地化字符串。
        /// </summary>
        internal static string AutoFormatLongLinesProperty {
            get {
                return ResourceManager.GetString("AutoFormatLongLinesProperty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Auto format on save 的本地化字符串。
        /// </summary>
        internal static string AutoFormatOnSave {
            get {
                return ResourceManager.GetString("AutoFormatOnSave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Whether to format the XML when it is saved 的本地化字符串。
        /// </summary>
        internal static string AutoFormatOnSaveDescription {
            get {
                return ResourceManager.GetString("AutoFormatOnSaveDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Background 的本地化字符串。
        /// </summary>
        internal static string BackgroundColor {
            get {
                return ResourceManager.GetString("BackgroundColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Background color for XML notepad workspace 的本地化字符串。
        /// </summary>
        internal static string BackgroundColorDescription {
            get {
                return ResourceManager.GetString("BackgroundColorDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Open File Dialog 的本地化字符串。
        /// </summary>
        internal static string BrowseButtonTooltip {
            get {
                return ResourceManager.GetString("BrowseButtonTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 CDATA 的本地化字符串。
        /// </summary>
        internal static string CDataColor {
            get {
                return ResourceManager.GetString("CDataColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Color of CData nodes 的本地化字符串。
        /// </summary>
        internal static string CDataColorDescription {
            get {
                return ResourceManager.GetString("CDataColorDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Change Error 的本地化字符串。
        /// </summary>
        internal static string ChangeErrorCaption {
            get {
                return ResourceManager.GetString("ChangeErrorCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Change node to {0} 的本地化字符串。
        /// </summary>
        internal static string ChangeNodeCommand {
            get {
                return ResourceManager.GetString("ChangeNodeCommand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Colors 的本地化字符串。
        /// </summary>
        internal static string ColorCategory {
            get {
                return ResourceManager.GetString("ColorCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 &amp;Color picker... 的本地化字符串。
        /// </summary>
        internal static string ColorPickerLabel {
            get {
                return ResourceManager.GetString("ColorPickerLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Comment 的本地化字符串。
        /// </summary>
        internal static string CommentColor {
            get {
                return ResourceManager.GetString("CommentColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Text color for comments 的本地化字符串。
        /// </summary>
        internal static string CommentColorDescription {
            get {
                return ResourceManager.GetString("CommentColorDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 File &apos;{0}&apos; does not exist. Do you need to create the file? 的本地化字符串。
        /// </summary>
        internal static string CreateFile {
            get {
                return ResourceManager.GetString("CreateFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Create New File 的本地化字符串。
        /// </summary>
        internal static string CreateNodeFileCaption {
            get {
                return ResourceManager.GetString("CreateNodeFileCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Connecting to {0} 的本地化字符串。
        /// </summary>
        internal static string CredentialDialog_DescriptionTextFormat {
            get {
                return ResourceManager.GetString("CredentialDialog.DescriptionTextFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Connect to {0} 的本地化字符串。
        /// </summary>
        internal static string CredentialDialog_TitleFormat {
            get {
                return ResourceManager.GetString("CredentialDialog.TitleFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Cut 的本地化字符串。
        /// </summary>
        internal static string CutCommand {
            get {
                return ResourceManager.GetString("CutCommand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Cut 的本地化字符串。
        /// </summary>
        internal static string CutSchemaCommand {
            get {
                return ResourceManager.GetString("CutSchemaCommand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 yyyy-MM-dd 的本地化字符串。
        /// </summary>
        internal static string DateFormat {
            get {
                return ResourceManager.GetString("DateFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 yyyy-MM-ddTHH:mm:ss 的本地化字符串。
        /// </summary>
        internal static string DateTimeFormat {
            get {
                return ResourceManager.GetString("DateTimeFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Delete 的本地化字符串。
        /// </summary>
        internal static string DeleteCommand {
            get {
                return ResourceManager.GetString("DeleteCommand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Do you want to discard the changes you&apos;ve made so far? 的本地化字符串。
        /// </summary>
        internal static string DiscardChanges {
            get {
                return ResourceManager.GetString("DiscardChanges", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Discard Changes 的本地化字符串。
        /// </summary>
        internal static string DiscardChangesCaption {
            get {
                return ResourceManager.GetString("DiscardChangesCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Attribute with the same name already exists 的本地化字符串。
        /// </summary>
        internal static string DuplicateAttribute {
            get {
                return ResourceManager.GetString("DuplicateAttribute", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Duplicate Error 的本地化字符串。
        /// </summary>
        internal static string DuplicateErrorCaption {
            get {
                return ResourceManager.GetString("DuplicateErrorCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The Dynamic Help tab contains some schema documentation 的本地化字符串。
        /// </summary>
        internal static string DynamicHelpAvailable {
            get {
                return ResourceManager.GetString("DynamicHelpAvailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Dynamic Help 的本地化字符串。
        /// </summary>
        internal static string DynamicHelpTab {
            get {
                return ResourceManager.GetString("DynamicHelpTab", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Edit Error 的本地化字符串。
        /// </summary>
        internal static string EditErrorCaption {
            get {
                return ResourceManager.GetString("EditErrorCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Edit Name 的本地化字符串。
        /// </summary>
        internal static string EditNameCommand {
            get {
                return ResourceManager.GetString("EditNameCommand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Edit Namespace 的本地化字符串。
        /// </summary>
        internal static string EditNamespaceCommand {
            get {
                return ResourceManager.GetString("EditNamespaceCommand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Edit 的本地化字符串。
        /// </summary>
        internal static string EditSchemaCommand {
            get {
                return ResourceManager.GetString("EditSchemaCommand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Edit Value 的本地化字符串。
        /// </summary>
        internal static string EditValueCommand {
            get {
                return ResourceManager.GetString("EditValueCommand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Element 的本地化字符串。
        /// </summary>
        internal static string ElementColor {
            get {
                return ResourceManager.GetString("ElementColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Text color for elements 的本地化字符串。
        /// </summary>
        internal static string ElementColorDescription {
            get {
                return ResourceManager.GetString("ElementColorDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Enable updates 的本地化字符串。
        /// </summary>
        internal static string EnableUpdate {
            get {
                return ResourceManager.GetString("EnableUpdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Whether to check for updates periodically 的本地化字符串。
        /// </summary>
        internal static string EnableUpdateDescription {
            get {
                return ResourceManager.GetString("EnableUpdateDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Error launching &apos;{0}&apos; 的本地化字符串。
        /// </summary>
        internal static string ErrorCreatingProcessPrompt {
            get {
                return ResourceManager.GetString("ErrorCreatingProcessPrompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Error List 的本地化字符串。
        /// </summary>
        internal static string ErrorListTab {
            get {
                return ResourceManager.GetString("ErrorListTab", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 File Changed 的本地化字符串。
        /// </summary>
        internal static string FileChagedOnDiskCaption {
            get {
                return ResourceManager.GetString("FileChagedOnDiskCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The file you are editing has been changed on disk.  Would you like to reload this file? 的本地化字符串。
        /// </summary>
        internal static string FileChagedOnDiskPrompt {
            get {
                return ResourceManager.GetString("FileChagedOnDiskPrompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Files Identical 的本地化字符串。
        /// </summary>
        internal static string FilesAreIdenticalCaption {
            get {
                return ResourceManager.GetString("FilesAreIdenticalCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Files are identical according to XML Diff 的本地化字符串。
        /// </summary>
        internal static string FilesAreIdenticalPrompt {
            get {
                return ResourceManager.GetString("FilesAreIdenticalPrompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Find Error 的本地化字符串。
        /// </summary>
        internal static string FindErrorCaption {
            get {
                return ResourceManager.GetString("FindErrorCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 No more matching nodes 的本地化字符串。
        /// </summary>
        internal static string FindNextDonePrompt {
            get {
                return ResourceManager.GetString("FindNextDonePrompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似  Find 的本地化字符串。
        /// </summary>
        internal static string FindWindowFindTitle {
            get {
                return ResourceManager.GetString("FindWindowFindTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似  Replace 的本地化字符串。
        /// </summary>
        internal static string FindWindowReplaceTitle {
            get {
                return ResourceManager.GetString("FindWindowReplaceTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Fonts 的本地化字符串。
        /// </summary>
        internal static string FontCategory {
            get {
                return ResourceManager.GetString("FontCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Font to use in XML notepad workspace 的本地化字符串。
        /// </summary>
        internal static string FontDesciption {
            get {
                return ResourceManager.GetString("FontDesciption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Font 的本地化字符串。
        /// </summary>
        internal static string FontPropertyName {
            get {
                return ResourceManager.GetString("FontPropertyName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Formatting Options 的本地化字符串。
        /// </summary>
        internal static string FormatCategory {
            get {
                return ResourceManager.GetString("FormatCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Avoid DTD validations 的本地化字符串。
        /// </summary>
        internal static string IgnoreDTDDescription {
            get {
                return ResourceManager.GetString("IgnoreDTDDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Ignore DTD 的本地化字符串。
        /// </summary>
        internal static string IgnoreDTDProperty {
            get {
                return ResourceManager.GetString("IgnoreDTDProperty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Illegal surrogate character pair 0x{0}, 0x{1} at position {2} in this text node. 的本地化字符串。
        /// </summary>
        internal static string IllegalSurrogatePair {
            get {
                return ResourceManager.GetString("IllegalSurrogatePair", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 href attribute is missing from your XInclude element 的本地化字符串。
        /// </summary>
        internal static string IncludeHRefRequired {
            get {
                return ResourceManager.GetString("IncludeHRefRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Indent char 的本地化字符串。
        /// </summary>
        internal static string IndentChar {
            get {
                return ResourceManager.GetString("IndentChar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The indent character to use 的本地化字符串。
        /// </summary>
        internal static string IndentCharDescription {
            get {
                return ResourceManager.GetString("IndentCharDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Indent level 的本地化字符串。
        /// </summary>
        internal static string IndentLevel {
            get {
                return ResourceManager.GetString("IndentLevel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Number of indent characters to use for one indent level 的本地化字符串。
        /// </summary>
        internal static string IndentLevelDescription {
            get {
                return ResourceManager.GetString("IndentLevelDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Insert Error 的本地化字符串。
        /// </summary>
        internal static string InsertErrorCaption {
            get {
                return ResourceManager.GetString("InsertErrorCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Insert 的本地化字符串。
        /// </summary>
        internal static string InsertNodeCommand {
            get {
                return ResourceManager.GetString("InsertNodeCommand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Character value {0} at position {1} in this text node is illegal in XML documents.  See http://www.w3.org/TR/2006/REC-xml-20060816/#NT-Char. 的本地化字符串。
        /// </summary>
        internal static string InvalidCharacter {
            get {
                return ResourceManager.GetString("InvalidCharacter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 InternalError: ISite has not been provided, so model cannot be found 的本地化字符串。
        /// </summary>
        internal static string ISiteMissing {
            get {
                return ResourceManager.GetString("ISiteMissing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Language Options 的本地化字符串。
        /// </summary>
        internal static string LanguageCategory {
            get {
                return ResourceManager.GetString("LanguageCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The language to select from XSD annotations 的本地化字符串。
        /// </summary>
        internal static string LanguageDescription {
            get {
                return ResourceManager.GetString("LanguageDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Language 的本地化字符串。
        /// </summary>
        internal static string LanguagePropertyName {
            get {
                return ResourceManager.GetString("LanguagePropertyName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Error Launching Process 的本地化字符串。
        /// </summary>
        internal static string LaunchErrorPrompt {
            get {
                return ResourceManager.GetString("LaunchErrorPrompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Loaded in {0} 的本地化字符串。
        /// </summary>
        internal static string LoadedTimeStatus {
            get {
                return ResourceManager.GetString("LoadedTimeStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Load Error 的本地化字符串。
        /// </summary>
        internal static string LoadErrorCaption {
            get {
                return ResourceManager.GetString("LoadErrorCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Error loading: {0}
        ///{1}
        ///
        ///Would you like to open it using Notepad? 的本地化字符串。
        /// </summary>
        internal static string LoadErrorPrompt {
            get {
                return ResourceManager.GetString("LoadErrorPrompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Very Long Lines 的本地化字符串。
        /// </summary>
        internal static string LongLineCaption {
            get {
                return ResourceManager.GetString("LongLineCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Long Lines 的本地化字符串。
        /// </summary>
        internal static string LongLineCategory {
            get {
                return ResourceManager.GetString("LongLineCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The text in this node contains some very long lines which may make editing this string very slow.  
        ///Would you like to reformat the text into multiple lines? 的本地化字符串。
        /// </summary>
        internal static string LongLinePrompt {
            get {
                return ResourceManager.GetString("LongLinePrompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 XML Notepad 的本地化字符串。
        /// </summary>
        internal static string MainFormTitle {
            get {
                return ResourceManager.GetString("MainFormTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 What is the maximum line length before prompting for reformatting? 的本地化字符串。
        /// </summary>
        internal static string MaximumLineLengthDescription {
            get {
                return ResourceManager.GetString("MaximumLineLengthDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Maximum Line Length 的本地化字符串。
        /// </summary>
        internal static string MaximumLineLengthProperty {
            get {
                return ResourceManager.GetString("MaximumLineLengthProperty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Move 的本地化字符串。
        /// </summary>
        internal static string MoveCommand {
            get {
                return ResourceManager.GetString("MoveCommand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Move Error 的本地化字符串。
        /// </summary>
        internal static string MoveErrorCaption {
            get {
                return ResourceManager.GetString("MoveErrorCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 New line character 的本地化字符串。
        /// </summary>
        internal static string NewLineChars {
            get {
                return ResourceManager.GetString("NewLineChars", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The character sequence to use for new lines.  &quot;\r&quot; means 0xD and &quot;\n&quot; means 0xA.  So &quot;\r\n&quot; gives you Windows style newlines. 的本地化字符串。
        /// </summary>
        internal static string NewLineCharsDescription {
            get {
                return ResourceManager.GetString("NewLineCharsDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 No byte order mark on save 的本地化字符串。
        /// </summary>
        internal static string NoByteOrderMark {
            get {
                return ResourceManager.GetString("NoByteOrderMark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Do not write any byte order mark at the beginning of the file for UTF-8 (0xef 0xbb 0xbf) or UTF-16 (0xff ffe) 的本地化字符串。
        /// </summary>
        internal static string NoByteOrderMarkDescription {
            get {
                return ResourceManager.GetString("NoByteOrderMarkDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Cannot edit name of node of type &apos;{0}&apos; 的本地化字符串。
        /// </summary>
        internal static string NodeNameNotEditable {
            get {
                return ResourceManager.GetString("NodeNameNotEditable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Missing Name  的本地化字符串。
        /// </summary>
        internal static string NodeNameRequiredCaption {
            get {
                return ResourceManager.GetString("NodeNameRequiredCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 You cannot edit the value of a node until you provide a node name. 的本地化字符串。
        /// </summary>
        internal static string NodeNameRequiredPrompt {
            get {
                return ResourceManager.GetString("NodeNameRequiredPrompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Cannot edit name of node, node not created yet! 的本地化字符串。
        /// </summary>
        internal static string NodeNotCreated {
            get {
                return ResourceManager.GetString("NodeNotCreated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Internal Error: node is not a child 的本地化字符串。
        /// </summary>
        internal static string NotAChild {
            get {
                return ResourceManager.GetString("NotAChild", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Nudge 的本地化字符串。
        /// </summary>
        internal static string NudgeCommand {
            get {
                return ResourceManager.GetString("NudgeCommand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Nudge Error 的本地化字符串。
        /// </summary>
        internal static string NudgeErrorCaption {
            get {
                return ResourceManager.GetString("NudgeErrorCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 XML files (*.xml)|*.xml|XSL files (*.xsl)|*.xsl|XSD files (*.xsd)|*.xsd|CSV files (*.csv)|*.csv|All files (*.*)|*.* 的本地化字符串。
        /// </summary>
        internal static string OpenFileFilter {
            get {
                return ResourceManager.GetString("OpenFileFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Paste 的本地化字符串。
        /// </summary>
        internal static string PasteCommand {
            get {
                return ResourceManager.GetString("PasteCommand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Paste Error 的本地化字符串。
        /// </summary>
        internal static string PasteErrorCaption {
            get {
                return ResourceManager.GetString("PasteErrorCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 PI 的本地化字符串。
        /// </summary>
        internal static string PiColor {
            get {
                return ResourceManager.GetString("PiColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Color of Processing Instruction nodes 的本地化字符串。
        /// </summary>
        internal static string PiColorDescription {
            get {
                return ResourceManager.GetString("PiColorDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The target file is read only, would you like to overwrite &apos;{0}&apos;? 的本地化字符串。
        /// </summary>
        internal static string ReadOnly {
            get {
                return ResourceManager.GetString("ReadOnly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Read Only File 的本地化字符串。
        /// </summary>
        internal static string ReadOnlyCaption {
            get {
                return ResourceManager.GetString("ReadOnlyCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Redo Error 的本地化字符串。
        /// </summary>
        internal static string RedoError {
            get {
                return ResourceManager.GetString("RedoError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Replace Complete 的本地化字符串。
        /// </summary>
        internal static string ReplaceCompleteCaption {
            get {
                return ResourceManager.GetString("ReplaceCompleteCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Replace Error 的本地化字符串。
        /// </summary>
        internal static string ReplaceErrorCaption {
            get {
                return ResourceManager.GetString("ReplaceErrorCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 This will reset all options to the built in defaults, are you sure you want to do that? 的本地化字符串。
        /// </summary>
        internal static string ResetOptionsPrompt {
            get {
                return ResourceManager.GetString("ResetOptionsPrompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Reset All Options 的本地化字符串。
        /// </summary>
        internal static string ResetOptionsPromptCaption {
            get {
                return ResourceManager.GetString("ResetOptionsPromptCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Cannot insert attributes at the root level 的本地化字符串。
        /// </summary>
        internal static string RootLevelAttributes {
            get {
                return ResourceManager.GetString("RootLevelAttributes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Cannot have anything before the XML declaration 的本地化字符串。
        /// </summary>
        internal static string RootLevelBeforeXmlDecl {
            get {
                return ResourceManager.GetString("RootLevelBeforeXmlDecl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Cannot have two top level elements 的本地化字符串。
        /// </summary>
        internal static string RootLevelElements {
            get {
                return ResourceManager.GetString("RootLevelElements", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Cannot insert text at the root level 的本地化字符串。
        /// </summary>
        internal static string RootLevelText {
            get {
                return ResourceManager.GetString("RootLevelText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 XML files (*.xml)|*.xml|XSL files (*.xsl)|*.xsl|XSD files (*.xsd)|*.xsd|All files (*.*)|*.* 的本地化字符串。
        /// </summary>
        internal static string SaveAsFilter {
            get {
                return ResourceManager.GetString("SaveAsFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Save Changes 的本地化字符串。
        /// </summary>
        internal static string SaveChangesCaption {
            get {
                return ResourceManager.GetString("SaveChangesCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Do you want to save your changes? 的本地化字符串。
        /// </summary>
        internal static string SaveChangesPrompt {
            get {
                return ResourceManager.GetString("SaveChangesPrompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Saved 的本地化字符串。
        /// </summary>
        internal static string SavedStatus {
            get {
                return ResourceManager.GetString("SavedStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Save Error 的本地化字符串。
        /// </summary>
        internal static string SaveErrorCaption {
            get {
                return ResourceManager.GetString("SaveErrorCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Save Errors 的本地化字符串。
        /// </summary>
        internal static string SaveErrorsCaption {
            get {
                return ResourceManager.GetString("SaveErrorsCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Lose XInclude Information 的本地化字符串。
        /// </summary>
        internal static string SaveExpandedIncludesCaption {
            get {
                return ResourceManager.GetString("SaveExpandedIncludesCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 You have expanded inline XIncludes, if you save this document you will lose the XInclude elements.  Are you sure you want to do that? 的本地化字符串。
        /// </summary>
        internal static string SaveExpandedIncludesPrompt {
            get {
                return ResourceManager.GetString("SaveExpandedIncludesPrompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Schema Error 的本地化字符串。
        /// </summary>
        internal static string SchemaError {
            get {
                return ResourceManager.GetString("SchemaError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Error loading schema &apos;{0}&apos;
        ///{1} 的本地化字符串。
        /// </summary>
        internal static string SchemaLoadError {
            get {
                return ResourceManager.GetString("SchemaLoadError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 System Exception of type {0}
        ///{1} 的本地化字符串。
        /// </summary>
        internal static string SystemError {
            get {
                return ResourceManager.GetString("SystemError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Text 的本地化字符串。
        /// </summary>
        internal static string TextColor {
            get {
                return ResourceManager.GetString("TextColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Color of text nodes 的本地化字符串。
        /// </summary>
        internal static string TextColorDescription {
            get {
                return ResourceManager.GetString("TextColorDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The specified text was not found 的本地化字符串。
        /// </summary>
        internal static string TextNotFoundPrompt {
            get {
                return ResourceManager.GetString("TextNotFoundPrompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 HH:mm:ss 的本地化字符串。
        /// </summary>
        internal static string TimeFormat {
            get {
                return ResourceManager.GetString("TimeFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Schema must define same target namespace 的本地化字符串。
        /// </summary>
        internal static string TNSMismatch {
            get {
                return ResourceManager.GetString("TNSMismatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Click here to execute XSLT transform 的本地化字符串。
        /// </summary>
        internal static string TransformButtonTooltip {
            get {
                return ResourceManager.GetString("TransformButtonTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Error Transforming XML 的本地化字符串。
        /// </summary>
        internal static string TransformErrorCaption {
            get {
                return ResourceManager.GetString("TransformErrorCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Type converter for type &apos;{0}&apos; not found. 的本地化字符串。
        /// </summary>
        internal static string TypeConvertError {
            get {
                return ResourceManager.GetString("TypeConvertError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Undo Error 的本地化字符串。
        /// </summary>
        internal static string UndoError {
            get {
                return ResourceManager.GetString("UndoError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Unexpected node type &apos;{0}&apos; 的本地化字符串。
        /// </summary>
        internal static string UnexpectedNodeType {
            get {
                return ResourceManager.GetString("UnexpectedNodeType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Unexpected token &apos;{0}&apos; at line {1} column {2} 的本地化字符串。
        /// </summary>
        internal static string UnexpectedToken {
            get {
                return ResourceManager.GetString("UnexpectedToken", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Version {1} of {0} is now available.  
        ///Do you want to visit the web page that describes this update? 的本地化字符串。
        /// </summary>
        internal static string UpdateAvailable {
            get {
                return ResourceManager.GetString("UpdateAvailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Update Available 的本地化字符串。
        /// </summary>
        internal static string UpdateAvailableCaption {
            get {
                return ResourceManager.GetString("UpdateAvailableCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Updates 的本地化字符串。
        /// </summary>
        internal static string UpdateCategory {
            get {
                return ResourceManager.GetString("UpdateCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Update location 的本地化字符串。
        /// </summary>
        internal static string UpdateLocation {
            get {
                return ResourceManager.GetString("UpdateLocation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Location of special XML file containing update information 的本地化字符串。
        /// </summary>
        internal static string UpdateLocationDescription {
            get {
                return ResourceManager.GetString("UpdateLocationDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 &amp;Browse... 的本地化字符串。
        /// </summary>
        internal static string UriBrowseLabel {
            get {
                return ResourceManager.GetString("UriBrowseLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 &lt;tr&gt;&lt;td&gt;&lt;/td&gt;&lt;td title=&apos;{0}&apos;&gt;&lt;b&gt; File in editor : {1}&lt;/b&gt;&lt;/td&gt;
        ///  &lt;td title=&apos;{2}&apos;&gt;&lt;b&gt; File to compare : {2}&lt;/b&gt;&lt;/td&gt;
        ///&lt;/tr&gt; 的本地化字符串。
        /// </summary>
        internal static string XmlDiffBody {
            get {
                return ResourceManager.GetString("XmlDiffBody", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 XML Diff Error 的本地化字符串。
        /// </summary>
        internal static string XmlDiffErrorCaption {
            get {
                return ResourceManager.GetString("XmlDiffErrorCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 You must provide a non-empty name, are you sure you want to leave this name empty? 的本地化字符串。
        /// </summary>
        internal static string XmlNameEmptyPrompt {
            get {
                return ResourceManager.GetString("XmlNameEmptyPrompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Name Error 的本地化字符串。
        /// </summary>
        internal static string XmlNameErrorCaption {
            get {
                return ResourceManager.GetString("XmlNameErrorCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        internal static byte[] XmlNotepadRegistration {
            get {
                object obj = ResourceManager.GetObject("XmlNotepadRegistration", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找类似 XSLT files (*.xslt;*.xsl)|*.xslt;*.xsl|All files (*.*)|*.* 的本地化字符串。
        /// </summary>
        internal static string XSLFileFilter {
            get {
                return ResourceManager.GetString("XSLFileFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Please enter location of XSLT stylesheet you want to use for transforming your XML document 的本地化字符串。
        /// </summary>
        internal static string XslFileNameTooltip {
            get {
                return ResourceManager.GetString("XslFileNameTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Untrusted Script Code 的本地化字符串。
        /// </summary>
        internal static string XslScriptCodeCaption {
            get {
                return ResourceManager.GetString("XslScriptCodeCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 This stylesheet contains untrusted script code.  
        ///Do you want to enable execution of this script code? 的本地化字符串。
        /// </summary>
        internal static string XslScriptCodePrompt {
            get {
                return ResourceManager.GetString("XslScriptCodePrompt", resourceCulture);
            }
        }
    }
}
